spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

    h2:
      console:
        enabled: true
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
      database: h2
      generate-ddl: off

logging:
  level:
    org:
      hibernate: trace
